### ISSUE TITLE
ModalSheet expand on search

### ISSUE THREAD

**Issue by SRomanova** [akbarpulatov/flutter_awesome_select#10]
Hi, 
I am trying to make the modalSheet to not expand after pressing on search field ( and keyboard appear) but I can not found such a property. Is there any? Or is there a method I need to override to prevent this behavior? 
Also, when I use the default search implementation, after clicking in search field, all items disappear like no results are matching. Is it possible to set it to take the all list of choices and filter it after entering a char?

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by akbarpulatov** [comment]
Issue is fixed in 834321de79dbb2b61befcfa8ddd97c90d2569c55
