### ISSUE TITLE
Problem with groupEnabled on null-safety application

### ISSUE THREAD

**Issue by DonWasyl** [akbarpulatov/flutter_awesome_select#13]
Hello, I noticed a problem with displaying list when I use `groupEnabled` on application with null-safety.
When we try open list on app with null-safety (`sdk: ">=2.12.0 <3.0.0"`) we get the error:
```type 'List<Widget?>' is not a subtype of type 'List<Widget>' in type cast```

Example app works because it is built without null-safety.

I made a simple fix for that, maybe isn't perfect, but it works.

https://github.com/akbarpulatov/flutter_awesome_select/pull/14

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by akbarpulatov** [comment]
Issue is fixed on 834321de79dbb2b61befcfa8ddd97c90d2569c55

**Comment by akbarpulatov** [comment]
it is on version 5.1.0

**Comment by akbarpulatov** [comment]
feel free to open again if you have it again.
