### ISSUE TITLE
List items are not refreshed when the items’ source e.g. a change notifier Provider sends an updated list

### ISSUE THREAD

**Issue by absar** [akbarpulatov/flutter_awesome_select#15]
List items are not refreshed when the items’ source e.g. a change notifier Provider sends an updated list. Rather the list disappears, or it does not refresh.
Issue, lets try to add a new item to the list, before adding there were 3 items, check the list items at the end, the items disappear, instead it should show 4 items:
![BeforeFix](https://user-images.githubusercontent.com/1186833/140627117-48374304-e517-4e7c-b5d4-57e74b5cffb9.gif)

Doing the same activity with fixed version from PR https://github.com/akbarpulatov/flutter_awesome_select/pull/12, in the below example lets try to add a new item to the list, before adding there were 3 items, and after adding, the list shows 4 items:
![FixedVersion](https://user-images.githubusercontent.com/1186833/140627127-79427699-e9ad-42a8-9336-2253e8783e2d.gif)

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by akbarpulatov** [comment]
Issue is fixed on 834321de79dbb2b61befcfa8ddd97c90d2569c55

**Comment by absar** [comment]
Issue is not fixed in the latest version, null safety is not going to fix the issue, rather you should merge the PR #12
