### ISSUE TITLE
Customisation of SmartSelect tile

### ISSUE THREAD

**Issue by WieFel** [akbarpulatov/flutter_awesome_select#20]
Hi,
Thanks for the literally awesome package! Unfortunately, I still have some problems with it.
I am using two expanded `SmartSelect` widgets within a row and I am having problems with the responsiveness/customisability of the tiles.
As can be seen, the `title` text of the left smart select is already wrapped into 2 lines but doesn't look very good:
<img width="520" alt="image" src="https://user-images.githubusercontent.com/8345062/145194820-2c418f6e-108e-47db-b2d4-a6d559820e91.png">
Also, if I have a multi selection and multiple items are selected, the title looks like this:
<img width="519" alt="image" src="https://user-images.githubusercontent.com/8345062/145195649-41724859-322b-43da-982b-2a53cce280c1.png">
If too many options are selected, the text overflows:
<img width="517" alt="image" src="https://user-images.githubusercontent.com/8345062/145195720-2ee23408-d14c-4d3f-9d42-8fd2ec11f0c9.png">

Actually I would need two things:
1. Be able to hide the title completely.  (currently, when setting `title: ""` I get an exception)
2. Be able to define text behaviour of title and selected item text: `maxLines` and `overflow` properties just like in Flutter's `Text` widget.

**Comment by akbarpulatov** [comment]
Hi, and sorry for the late reply.
Thank you for your kind words))
Probably, we will be adding this in next sunday's release).

**Comment by WieFel** [comment]
@akbarpulatov thank you very much for the response!

As a small workaround I am currently just manually displaying the current value inside the `title`, and disabled the SmartSelect-provided showing of the current value instead.

**Comment by akbarpulatov** [comment]
Hi! Can you share your code?
By the way, you should not have an exception when `title: ""`.

**Comment by akbarpulatov** [comment]
I created a discord channel for this purpose: https://discord.gg/2HAKeZwPsQ

**Comment by akbarpulatov** [comment]
Maybe you want to use custom tile and set your own Text Widget with your properties like this: 

```
import 'package:flutter/material.dart';
import 'package:flutter_awesome_select/flutter_awesome_select.dart';

class FeaturesMultiPage extends StatefulWidget {
  @override
  _FeaturesMultiPageState createState() => _FeaturesMultiPageState();
}

class _FeaturesMultiPageState extends State<FeaturesMultiPage> {

  List<String>? _chosenSeries = ['a'];

  List<S2Choice<String>> _series = [
    S2Choice<String>(value: 'a', title: 'a'),
    S2Choice<String>(value: 'b', title: 'b'),
    S2Choice<String>(value: 'c', title: 'c'),
    S2Choice<String>(value: 'd', title: 'd'),
    S2Choice<String>(value: 'e', title: 'e'),
  ];

  List<String>? _chosenPeriod = ['live'];

  List<S2Choice<String>> _periods = [
    S2Choice<String>(value: 'live', title: 'Live'),
    S2Choice<String>(value: 'another_pediod_1', title: 'Another Period 1'),
    S2Choice<String>(value: 'another_pediod_2', title: 'Another Period 2'),
  ];


  @override
  Widget build(BuildContext context) {
    return Row(
      children: <Widget>[
        Flexible(
          flex: 5,
          child: SmartSelect<String>.multiple(
            title: 'Period title',
            selectedValue: _chosenPeriod,
            choiceItems: _periods,
            tileBuilder: (context, state){
              return S2Tile.fromState(state,
                title: Text('Period', overflow: TextOverflow.ellipsis, maxLines: 1,),
              );
            },
            onChange: (selected) => setState(() => _chosenPeriod = selected?.value),
          ),
        ),
        const Divider(indent: 20),
        Flexible(
          flex: 5,
          child: SmartSelect<String>.multiple(
            title: 'Series title',
            selectedValue: _chosenSeries,
            tileBuilder: (context, state){
              return S2Tile.fromState(state,
                title: Text('Series', overflow: TextOverflow.ellipsis, maxLines: 1,),
              );
            },
            choiceItems: _series,
            onChange: (selected) => setState(() => _chosenSeries = selected?.value),
          ),
        ),
      ],
    );
  }
}

```
![IMG_0143](https://user-images.githubusercontent.com/27597344/148049465-1d7ad012-f625-48fa-9d67-0397fb363dc8.PNG)



P.S. I recommend using `SmartSelect` in a column layout. But, if you want to make a row of multiple `SmartSelect` widgets, then you'd rather use tile and value to be in a column ( set `isTwoLine: true,`).
Result:
![IMG_0144](https://user-images.githubusercontent.com/27597344/148049635-f1789fb1-38b7-4f1e-9eaa-3d2eba37213e.PNG)

![IMG_0145](https://user-images.githubusercontent.com/27597344/148049862-2260cb1c-5055-42c3-95d4-d478ce51c05a.PNG)

Hope this helps!
Wait for your reply.

**Comment by akbarpulatov** [comment]
> Hi, and sorry for the late reply. Thank you for your kind words)) Probably, we will be adding this in next sunday's release).

Actually this approach was not effective)) So you can share your ideas if you have

**Comment by WieFel** [comment]
> P.S. I recommend using `SmartSelect` in a column layout. But, if you want to make a row of multiple `SmartSelect` widgets, then you'd rather use tile and value to be in a column ( set `isTwoLine: true,`). Result: ![IMG_0144](https://user-images.githubusercontent.com/27597344/148049635-f1789fb1-38b7-4f1e-9eaa-3d2eba37213e.PNG)
> 
> ![IMG_0145](https://user-images.githubusercontent.com/27597344/148049862-2260cb1c-5055-42c3-95d4-d478ce51c05a.PNG)
> 
> Hope this helps! Wait for your reply.

@akbarpulatov Actually this helped, thank you!
For now, I am good!
