### ISSUE TITLE
A value of type 'Color?' can't be assigned to a variable of type 'Color'

### ISSUE THREAD

**Issue by MartimTSilva** [akbarpulatov/flutter_awesome_select#26]
I can't import the package without getting errors.
I've migrated my project to null-safety, and now just by importing awesome_select package I get these errors.
![image](https://user-images.githubusercontent.com/43602260/152528730-d694a762-8db6-42be-8fca-5263344ba9de.png)

**Comment by FelipeSamuel** [comment]
some problem

**Comment by explorova** [comment]
same here

**Comment by SuperKMan** [comment]
got the same error too.

**Comment by Saulmarti** [comment]
I have de same error.
To resolve it i downgrade the version of Flutter, the problem is with the version 1.10 of Flutter.

**Comment by vasilich6107** [comment]
> > 
> 
> 
> 
> I hit this error as soon as I upgraded to flutter 2.10.0.   My app is not yet using full null-safety, I suspect flutter 2.10 is forcing, or assuming, something along those lines by default.

Why not to migrate to null safety?

**Comment by explorova** [comment]
Still waiting on map_controller
  
  
   
  
  
   
    On 02/06/2022 1:09 AM Vasiliy Ditsyak ***@***.***> wrote:
   
   
    
   
   
    
   
   
   
    
    I hit this error as soon as I upgraded to flutter 2.10.0. My app is not yet using full null-safety, I suspect flutter 2.10 is forcing, or assuming, something along those lines by default.
   
   Why not to migrate to null safety?

**Comment by WieFel** [comment]
> I can't import the package without getting errors. I've migrated my project to null-safety, and now just by importing awesome_select package I get these errors. ![image](https://user-images.githubusercontent.com/43602260/152528730-d694a762-8db6-42be-8fca-5263344ba9de.png)

+1

**Comment by Dagmawi-Asfaw-CH** [comment]
i had the same problem when i upgraded to flutter 2.10.  it was fixed when I downgraded to version 2.8.1 on stable channel.

**Comment by youannis-aziz** [comment]
same problem after upgrading

**Comment by gelintonx** [comment]
Same problem here

**Comment by oncleguigs** [comment]
Same problem here

**Comment by triopu** [comment]
I changed package to smart_select because of this issue

**Comment by deddybear** [comment]
hi, someone can help newest update in this repository to pub.dev/packages ? please :(

**Comment by vasilich6107** [comment]
@MartimTSilva @FelipeSamuel @explorova @SuperKMan @Saulmarti @WieFel @Dagmawi-Asfaw-CH @youannis-aziz @gelintonx @oncleguigs @powerhai @FelipeSamuel @deddybear 
Fixed in https://pub.dev/packages/flutter_awesome_select/versions/6.1.2-beta

**Comment by Mathys-Rituper** [comment]
> change dependence for
> 
> awesome_select: git: url: https://github.com/Flutter-Fox/flutter_awesome_select.git ref: hotfix-5.1.0

Sorry for bothering with such a basic question (I'm a beginner with Flutter) but is it to be done in pubspec.yml or pubspec.lock ? I can't get it to work in neither of the files

**Comment by akbarpulatov** [comment]
Fixed in #27
