### ISSUE TITLE
tileBuilder error in multiple

### ISSUE THREAD

**Issue by Saulmarti** [akbarpulatov/flutter_awesome_select#6]
ERROR 

type '(BuildContext, S2MultiState<String>) => S2Tile<String>' is not a subtype of type '((BuildContext, S2MultiState<String?>) => Widget)?'

`SmartSelect<String>.multiple(
      title: translate('FILTER.genres'),
      selectedValue: widget.filters.generes,
      onChange: (selected) {
        setState(() => widget.filters.generes = selected!.value);
      },
      choiceItems: options,
      placeholder: translate("FILTER.select_more"),
      modalType: S2ModalType.bottomSheet,
      tileBuilder: (context, state) {
        return S2Tile.fromState(
          state,
          isTwoLine: true,
        );
      },
    );`

**Comment by vasilich6107** [comment]
@Saulmarti this is due to the issues with null safety migration

**Comment by DonWasyl** [comment]
Yup `SmartSelect<String?>.multiple(..)` instead of `SmartSelect.multiple<String>(..)` helps.
But I was using `flutter_smart_select` with `null-safety` branch and I hadn't this problem before.
Now this issue is blocker for me, because I would have to change a lot of types to start using this package :<

**Comment by vasilich6107** [comment]
@DonWasyl @SRomanova @journeystamps @Eider3a @Saulmarti 
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by akbarpulatov** [comment]
Issue is fixed on 834321de79dbb2b61befcfa8ddd97c90d2569c55.
